"use client";

import { Scale, FileSignature, Download, ShieldCheck, FileText, CheckCircle2, Clock, AlertTriangle } from "lucide-react";

export default function LegalClient({ rider, guarantors }: { rider: any, guarantors: any[] }) {
  
  const hpaUrl = rider.hpaAgreementUrl ? `${rider.hpaAgreementUrl}?fl_attachment=YUSDAAM_HPA_${rider.firstName}_${rider.lastName}.pdf` : null;

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in duration-500 pb-20">
      
      {/* Header */}
      <div>
        <h1 className="text-2xl sm:text-4xl font-black uppercase tracking-wider mb-2">Legal Vault</h1>
        <p className="text-sm text-slate-light">Secure storage for your digitally executed contracts and surety deeds.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* LEFT COLUMN: PRIMARY DOCUMENTS */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Hire Purchase Agreement Card */}
          <div className="bg-void-dark border border-cobalt/20 rounded-xl p-6 sm:p-8 shadow-lg relative overflow-hidden">
            <div className="absolute -right-6 -top-6 opacity-5">
              <Scale size={150} />
            </div>

            <div className="relative z-10">
              <div className="flex items-center gap-3 border-b border-cobalt/20 pb-4 mb-6">
                <div className="p-3 bg-cobalt/10 rounded-xl">
                  <FileSignature size={24} className="text-cobalt" />
                </div>
                <div>
                  <h2 className="text-lg font-black text-crisp-white uppercase tracking-wide">Hire Purchase Agreement</h2>
                  <p className="text-xs text-slate-light font-medium">Your primary asset allocation contract</p>
                </div>
              </div>

              {hpaUrl ? (
                <div className="bg-void-light/5 border border-cobalt/30 rounded-xl p-6 flex flex-col sm:flex-row justify-between items-center gap-6">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-emerald-500/10 rounded-full flex items-center justify-center shrink-0">
                      <ShieldCheck size={24} className="text-emerald-400" />
                    </div>
                    <div>
                      <p className="text-sm font-bold text-crisp-white uppercase tracking-wider">Executed & Secured</p>
                      <p className="text-[10px] text-slate-light uppercase tracking-widest mt-1">Digital Signature Appended</p>
                    </div>
                  </div>
                  
                  <a 
                    href={hpaUrl} 
                    download
                    className="w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3.5 bg-cobalt hover:bg-cobalt/90 text-crisp-white font-bold uppercase tracking-wider text-xs rounded-xl transition-all shadow-[0_0_15px_rgba(77,148,255,0.3)] shrink-0"
                  >
                    <Download size={16} /> Download PDF
                  </a>
                </div>
              ) : (
                <div className="text-center py-8 bg-void-light/5 border border-dashed border-cobalt/30 rounded-xl">
                  <Clock size={32} className="text-slate-light/40 mx-auto mb-3" />
                  <p className="text-sm font-bold text-crisp-white uppercase tracking-wider mb-1">Pending Execution</p>
                  <p className="text-xs text-slate-light">Your legal agreement will appear here once generated by the Administrator.</p>
                </div>
              )}
            </div>
          </div>

          {/* Legal Disclaimers */}
          <div className="bg-signal-red/5 border border-signal-red/20 rounded-xl p-6 flex gap-4 items-start">
            <div className="p-3 bg-signal-red/10 rounded-full shrink-0 text-signal-red">
              <AlertTriangle size={20} />
            </div>
            <div>
              <h4 className="text-sm font-bold text-crisp-white uppercase tracking-wider mb-2">Binding Nature of Digital Signatures</h4>
              <p className="text-xs text-slate-light leading-relaxed">
                In accordance with the Nigerian Evidence Act (2011), the digital signatures, timestamps, and IP addresses captured and affixed to the documents in this vault carry the exact legal weight, validity, and enforceability as physical ink signatures on paper.
              </p>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: GUARANTORS */}
        <div className="space-y-6">
          <div className="bg-void-dark border border-cobalt/20 rounded-xl p-6 shadow-lg h-full">
            <h3 className="font-bold border-b border-cobalt/20 pb-3 mb-6 uppercase tracking-wider flex items-center gap-2">
              <FileText size={18} className="text-cobalt"/> Guarantor Deeds
            </h3>

            <div className="space-y-4">
              {guarantors.map((g: any, index: number) => {
                const isExecuted = g.status !== "PENDING";
                
                return (
                  <div key={g.id || index} className="p-4 bg-void-light/5 border border-cobalt/10 rounded-xl">
                    <p className="text-[10px] text-slate-light font-bold uppercase tracking-widest mb-2">Surety {index + 1}</p>
                    <p className="text-sm font-black text-crisp-white uppercase tracking-wider mb-1">{g.firstName} {g.lastName}</p>
                    <p className="text-xs text-slate-light capitalize mb-4">{g.relationship}</p>
                    
                    {isExecuted ? (
                      <div className="flex items-center gap-2 px-3 py-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold uppercase tracking-wider text-[10px] rounded-lg">
                        <CheckCircle2 size={14} /> Sworn Attestation Executed
                      </div>
                    ) : (
                      <div className="flex items-center gap-2 px-3 py-2 bg-void-light/10 border border-void-light/20 text-slate-light font-bold uppercase tracking-wider text-[10px] rounded-lg">
                        <Clock size={14} /> Awaiting Signature
                      </div>
                    )}
                  </div>
                );
              })}

              {guarantors.length === 0 && (
                <p className="text-xs text-slate-light italic text-center py-4">No guarantors assigned.</p>
              )}
            </div>

            <div className="mt-6 pt-4 border-t border-cobalt/20">
              <p className="text-[10px] text-slate-light leading-relaxed">
                <strong className="text-crisp-white">Note:</strong> Guarantor Identity cards, utility bills, and sworn digital signatures are held in trust by YUSDAAM Administration for enforcement purposes.
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
